 CREATE SCHEMA IF NOT EXISTS ANY_REPORT;

 CREATE TABLE IF NOT EXISTS ANY_REPORT.ACC_TEST_SUMMARY
 (
     DATE_AUTHORISED VARCHAR(10)     NOT NULL,
     THE_SYSTEM          VARCHAR(200)    NOT NULL,
     ABC_VALUE           VARCHAR(200)    NOT NULL,
     DEFG_VALUE          VARCHAR(200)    NOT NULL
 );