CREATE SCHEMA IF NOT EXISTS ANY_REPORT;

CREATE TABLE IF NOT EXISTS ANY_REPORT.V_CIS_TO_CCMS_INVOICE_SUMMARY
(
    DATE_AUTHORISED_CIS VARCHAR(10)     NOT NULL,
    THE_SYSTEM          VARCHAR(200)    NOT NULL,
    CIS_VALUE           VARCHAR(200)    NOT NULL,
    CCMS_VALUE          VARCHAR(200)    NOT NULL
);