name: New Deploy to dev
on:
  push:
    branches:
      - feature/lpf-535b
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-tests ]

env:
  USERNAME: ${{ secrets.OPENAPI_PACKAGE_USER }}
  PASSWORD: ${{ secrets.OPENAPI_PACKAGE_PASSWORD }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          path: testCode

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Checkout source code repo
        uses: actions/checkout@v4
        with:
          repository: ministryofjustice/payforlegalaid
          path: sourceCode

      - name: variable test
        run: |
          echo "This is the value of the secret - testing"
          echo ${{ secrets.MY_TE_VARBE }}
          echo ${{ secrets.DM_TEST_VALUE }}
          echo ${{ secrets.MY_TE_VARBE }}
          echo ${{ secrets.MOJFIN_DEV_READ_USERNAME }}
          
      

      - name: Build source code
        run: |
          cd sourceCode
          
          mvn -B -DskipTests clean install -s .github/settings.xml

      - name: Run tests
        run: |
          cd testCode
          pwd && ls -l 
          mvn dependency:tree 
          mvn -B clean test -s .github/settings.xml  \
              -DMOJFIN_DB_URL= ${{ secrets.MOJFIN_URL }} \
              -DMOJFIN_DEV_READ_USERNAME= ${{ secrets.MOJFIN_READ_USERNAME }} \
              -DMOJFIN_DEV_READ_PASSWORD= ${{ secrets.MOJFIN_READ_PASSWORD }} \
              -DMOJFIN_DEV_WRITE_USERNAME=${{ secrets.MOJFIN_WRITE_USERNAME }} \
              -DMOJFIN_DEV_WRITE_USERNAME=${{ secrets.MOJFIN_WRITE_PASSWORD }}

        shell:
          bash
