name: New Deploy to dev
on:
  push:
    branches:
      - feature/lpf-535b
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-tests ]

env:
  USERNAME: ${{ secrets.OPENAPI_PACKAGE_USER }}
  PASSWORD: ${{ secrets.OPENAPI_PACKAGE_PASSWORD }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          path: testCode

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Checkout source code repo
        uses: actions/checkout@v4
        with:
          repository: ministryofjustice/payforlegalaid
          path: sourceCode

      - name: Build source code
        run: |
          cd sourceCode
          mvn -B -DskipTests clean install -s .github/settings.xml

      - name: Manually Install Oracle JDBC
        run: |
          pwd && ls -l
          cd testCode
          pwd && ls -l
          mvn install:install-file \
            -Dfile=lib/ojdbc11.jar \
            -DgroupId=com.oracle.database.jdbc \
            -DartifactId=ojdbc11 \
            -Dversion=23.7.0.25.01 \
            -Dpackaging=jar

      - name: Run tests
        run: |
          cd testCode
          pwd && ls -l 
          mvn dependency:tree 
          mvn -B clean test -s .github/settings.xml  \
              -DGPFD_DATASOURCE_READY-ONLY_URL= ${{ secrets.MOJFIN_URL }} \
              -DGPFD_DATASOURCE_READY-ONLY_USERNAME= ${{ secrets.MOJFIN_READ_USERNAME }} \
              -DGPFD_DATASOURCE_READY-ONLY_PASSWORD= ${{ secrets.MOJFIN_READ_PASSWORD }} \
              -DGPFD_DATASOURCE_WRITE_URL= ${{ secrets.MOJFIN_URL }} \
              -DGPFD_DATASOURCE_WRITE_USERNAME=${{ secrets.MOJFIN_WRITE_USERNAME }} \
              -DGPFD_DATASOURCE_WRITE_PASSWORD=${{ secrets.MOJFIN_WRITE_PASSWORD }}

        shell:
          bash
