name: Deploy to dev NEW
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-tests ]

env:
  USERNAME: ${{ secrets.OPENAPI_PACKAGE_USER }}
  PASSWORD: ${{ secrets.OPENAPI_PACKAGE_PASSWORD }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          path: testCode

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout source code repo
        uses: actions/checkout@v4
        with:
          repository: ministryofjustice/payforlegalaid
          path: sourceCode

      - name: Build source code
        run: |
          cd sourceCode
          mvn -B -DskipTests clean install -s .github/settings.xml

      - name: Run tests
        run: |
          cd testCode
          pwd && ls -l 
          mvn -B clean test -s .github/settings.xml  \
              -DGPFD_DATASOURCE_READY-ONLY_URL= ${{ secrets.MOJFIN_URL }} \
              -DGPFD_DATASOURCE_READY-ONLY_USERNAME= ${{ secrets.MOJFIN_READ_USERNAME }} \
              -DGPFD_DATASOURCE_READY-ONLY_PASSWORD= ${{ secrets.MOJFIN_READ_PASSWORD }} \
              -DGPFD_DATASOURCE_WRITE_URL= ${{ secrets.MOJFIN_URL }} \
              -DGPFD_DATASOURCE_WRITE_USERNAME=${{ secrets.MOJFIN_WRITE_USERNAME }} \
              -DGPFD_DATASOURCE_WRITE_PASSWORD=${{ secrets.MOJFIN_WRITE_PASSWORD }}

        shell:
          bash
